version: '3.1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_PORT=8080
    volumes:
      - ./keycloak-export:/opt/keycloak/data/import
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydatabasename
    volumes:
      - postgres_data:/opt/postgres/data
  gateway:
    image: pepinillojr/tpi-backend:gateway
    depends_on:
      - keycloak
    ports:
      - "8082:8082"
  pedidos:
    image: pepinillojr/tpi-backend:pedidos-service
    expose:
      - "8001"
    depends_on:
      - db
  depositos:
    image: pepinillojr/tpi-backend:depositos-service
    expose:
      - "8003"
    depends_on:
      - db
      - pedidos
    command: sh -c "sleep 10 && java -jar $(ls *.jar)"

  camiones:
    image: pepinillojr/tpi-backend:camiones-service
    expose:
      - "8002"
    depends_on:
      - db
      - pedidos
    command: sh -c "sleep 10 && java -jar $(ls *.jar)"
  osrm:
    image: osrm/osrm-backend:latest
    platform: linux/amd64
    container_name: osrm
    ports:
    - "5000:5000"
    volumes:
    - ./osrm-data:/data
    command: >
      osrm-routed /data/argentina-latest.osrm
volumes:
  keycloak_data:
  postgres_data:

